/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQLMateDesigner.Pan.SubPan;

/**
 *
 * @author profnagy
 */
public class JpButtons3 extends javax.swing.JPanel {

    private ButtonThunk Okay;
    private ButtonThunk Cancel;
    private ButtonThunk Help;

    /**
     * Creates new form JpOkayCanHelp
     */
    public JpButtons3() {
        initComponents();

    }

    public void set(final ButtonThunk Okay, final ButtonThunk Cancel, final ButtonThunk Help) {
        this.Okay = Okay;
        this.jbOkay.setText(Okay.getText());

        this.Cancel = Cancel;
        this.jbCancel.setText(Cancel.getText());

        this.Help = Help;
        this.jbHelp.setText(Help.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbOkay = new javax.swing.JButton();
        jbHelp = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        jbOkay.setText(" Okay ");
        jbOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkayActionPerformed(evt);
            }
        });
        add(jbOkay);

        jbHelp.setText(" Help ");
        jbHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHelpActionPerformed(evt);
            }
        });
        add(jbHelp);

        jbCancel.setText(" Cancel ");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        add(jbCancel);
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkayActionPerformed
        if (this.Okay != null) {
            this.Okay.getAction().actionPerformed(evt);
        }
    }//GEN-LAST:event_jbOkayActionPerformed

    private void jbHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHelpActionPerformed
        if (this.Help != null) {
            this.Help.getAction().actionPerformed(evt);
        }
    }//GEN-LAST:event_jbHelpActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        if (this.Cancel != null) {
            this.Cancel.getAction().actionPerformed(evt);
        }
    }//GEN-LAST:event_jbCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbHelp;
    private javax.swing.JButton jbOkay;
    // End of variables declaration//GEN-END:variables
}
