/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQLMateDesigner.Pan.SubPan;

import javax.swing.JButton;

/**
 *
 * @author profnagy
 */
public class JpProjects extends javax.swing.JPanel {

    /**
     * Creates new form JpProjects
     */
    public JpProjects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpOkayCanHelp1 = new SQLMateDesigner.Pan.SubPan.JpButtons3();
        jpProjectList1 = new SQLMateDesigner.Pan.SubPan.JpProjectList();

        setLayout(new java.awt.BorderLayout());
        add(jpOkayCanHelp1, java.awt.BorderLayout.CENTER);
        add(jpProjectList1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SQLMateDesigner.Pan.SubPan.JpButtons3 jpOkayCanHelp1;
    private SQLMateDesigner.Pan.SubPan.JpProjectList jpProjectList1;
    // End of variables declaration//GEN-END:variables

    public void setTopOptions(ButtonThunk Okay, ButtonThunk Cancel, ButtonThunk Help) {
        this.jpOkayCanHelp1.set(Okay, Cancel, Help);
    }
}
