/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQLMateDesigner.Pan.SubPan;

import SQLMateDesigner.DB.SqlMateProject;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author profnagy
 */
public class JpProjectList extends javax.swing.JPanel {

    private DefaultListModel lbModel;
    private ActionListener edit = null;
    private ActionListener create = null;

    /**
     * Creates new form JpSqlColumnList
     */
    public JpProjectList() {
        initComponents();
        lbModel = new DefaultListModel();
        this.jlstCols.setModel(lbModel);
    }

    public void set(List<SqlMateProject> data, ActionListener edit, ActionListener create) {
        if (data == null) {
            return;
        }
        this.edit = edit;
        this.create = create;

        this.lbModel.clear();
        for (SqlMateProject ref : data) {
            if (ref == null) {
                continue;
            }
            lbModel.add(0, ref.getProjectName());
        }
        this.jlstCols.setModel(lbModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlstCols = new javax.swing.JList();
        jToolBar1 = new javax.swing.JToolBar();
        jbCreate = new javax.swing.JButton();
        jbEdit = new javax.swing.JButton();
        jbDelete = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(" SQLMate Projects "));
        setLayout(new java.awt.BorderLayout());

        jlstCols.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlstCols.setPreferredSize(new java.awt.Dimension(52, 200));
        jScrollPane1.setViewportView(jlstCols);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setRollover(true);

        jbCreate.setText(" New Project ");
        jbCreate.setFocusable(false);
        jbCreate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbCreate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbCreate);

        jbEdit.setText(" Delete Project ");
        jbEdit.setFocusable(false);
        jbEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbEdit);

        jbDelete.setText("Edit Project ");
        jbDelete.setFocusable(false);
        jbDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbDelete);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbCreate;
    private javax.swing.JButton jbDelete;
    private javax.swing.JButton jbEdit;
    private javax.swing.JList jlstCols;
    // End of variables declaration//GEN-END:variables
}
