/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SQLMateDesigner.Pan;

/**
 *
 * @author profnagy
 */
public class JpProjects extends javax.swing.JPanel {

    /**
     * Creates new form JpProjects
     */
    public JpProjects() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpProjects1 = new SQLMateDesigner.Pan.SubPan.JpProjects();

        setLayout(new java.awt.CardLayout());
        add(jpProjects1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private SQLMateDesigner.Pan.SubPan.JpProjects jpProjects1;
    // End of variables declaration//GEN-END:variables
}
